---
title: "tcga_clinical_data"
author: "Patrick Garr"
date: "3/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(psych)
library(tidyverse)
library(gridExtra)
library(corrplot)
library(patchwork)
library(readxl)
library(MASS)
library(ROCR)
library(caret)
library(gmodels)
library(caTools)
library(class)
library(gridExtra)
library(factoextra)

set.seed(210)
```

```{r}
tcga.clinical.data <- read.csv("coad_tcga_clinical_data.csv", sep = ",",
         header = TRUE, stringsAsFactors = TRUE)

# Using domain knowledge to select only relevant features
tcga.clinical.df <- tcga.clinical.data[c("Sample.ID", "Diagnosis.Age", "Neoplasm.Disease.Stage.American.Joint.Committee.on.Cancer.Code",  "Cancer.Type.Detailed", "Disease.Free.Status", "Ethnicity.Category", "Form.completion.date", "Fraction.Genome.Altered", "Patient.Height", "Prior.Cancer.Diagnosis.Occurence", "Year.Cancer.Initial.Diagnosis", "Is.FFPE",  "Mutation.Count", "Overall.Survival..Months.", "Overall.Survival.Status",  "Patient.Primary.Tumor.Site", "Race.Category", "Surgical.Margin.Resection.Status", "Sample.Initial.Weight", "Sample.Type", "Sex", "Longest.Dimension", "Shortest.Dimension", "Tumor.Tissue.Site", "Specimen.Second.Longest.Dimension", "Tissue.Source.Site", "Person.Neoplasm.Status", "Patient.Weight")]

tcga.clinical.df$Year.Cancer.Initial.Diagnosis <- as.factor(tcga.clinical.df$Year.Cancer.Initial.Diagnosis)

# 0 = living, 1 = deceased
# Replacing the outcome to just be 0s and 1s for later data analysis

tcga.clinical.df$Overall.Survival.Status <- as.character(tcga.clinical.df$Overall.Survival.Status)
tcga.clinical.df$Overall.Survival.Status <- replace(tcga.clinical.df$Overall.Survival.Status, tcga.clinical.df$Overall.Survival.Status == "0:LIVING","0")
tcga.clinical.df$Overall.Survival.Status <- replace(tcga.clinical.df$Overall.Survival.Status, tcga.clinical.df$Overall.Survival.Status == "1:DECEASED","1")
tcga.clinical.df$Overall.Survival.Status <- as.factor(tcga.clinical.df$Overall.Survival.Status)
                            
tcga.scaled <- tcga.clinical.df
tcga.scaled[c(2,8:9,13:14,19,22:23,25,28)] <- scale(tcga.scaled[c(2,8:9,13:14,19,22:23,25,28)], center = TRUE)
    
# summary(tcga.clinical.df)                        
# summary(tcga.scaled)
```

```{r}
# PCA

# Looking at number of missing variables in numerical features
apply(X = is.na(tcga.scaled[c(2,8:9,13:14,19,22:23,25,28)]), MARGIN = 2, FUN = sum)

# It appears that the weights/heights are mostly related - typically if one is measured the other one is too -> design feature?
# Also appears that if the specimen was taken then it has measurements
# Removing Sample.Initial.Weight as >80% of variables are missing, others might require imputation or deletion

# Testing to see how many variables would remain -> some kind of imputation will definitely be required
na.remove.test <- tcga.scaled[c(2,8:9,14,28)]
na.remove.test <- na.omit(na.remove.test)
# Starting with only 5 variables for pca

prc.tcga =prcomp(na.remove.test, scale=FALSE)
get_eig(prc.tcga)
prc.tcga$rotation
fviz_eig(prc.tcga, addlabels = TRUE)
fviz_pca_biplot(prc.tcga, repel = TRUE)

```

```{r}
# Small enough sample that only going to be doing 70% split to have enough in test set

clin.sample1 = sample.split(tcga.clinical.df$Overall.Survival.Status, SplitRatio = 0.7)
train.df1 = subset(tcga.clinical.df, clin.sample1 == TRUE)
test.df1 = subset(tcga.clinical.df, clin.sample1 == FALSE)
train.df1.labels <- train.df1$Overall.Survival.Status
test.df1.labels <- test.df1$Overall.Survival.Status

```

```{r}

boxplot1 <- ggplot(tcga.clinical.df, aes(Overall.Survival..Months., Overall.Survival.Status))+
  geom_boxplot(outlier.colour="red")+
  coord_flip()+
  labs(title='Mutation Count vs. Overall Survival Status')+
  theme(plot.title = element_text(hjust = 0.5))
boxplot1

# boxplot2 <- ggplot(tcga.clinical.df, aes(Diagnosis.Age, Overall.Survival.Status))+
#   geom_boxplot(outlier.colour="red")+
#   coord_flip()+
#   labs(title='Diagnosis Age vs. Tumor Stage')+
#   theme(plot.title = element_text(hjust = 0.5))
# 
# mean_mut <- mean(tcga.clinical.df$Mutation.Count)
# sd_mut <- sd(tcga.clinical.df$Mutation.Count)
# 
# mut_outliers <- filter(tcga.clinical.df, Mutation.Count > mean_mut + 3*sd_mut | Mutation.Count < mean_mut - 3*sd_mut)
# 
# tgca_no_mut_outliers <- setdiff(tcga.clinical.df,mut_outliers)
# 
# boxplot3 <- ggplot(tgca_no_mut_outliers, aes(Mutation.Count, Overall.Survival.Status))+
#   geom_boxplot(outlier.colour="red")+
#   coord_flip()+
#   labs(title='Mutation Count vs. Tumor Stage - No Outliers')+
#   theme(plot.title = element_text(hjust = 0.5))
# # 
# # mut_plot = ggplot(coad_df, aes(x=Patient.ID, fill = Mutation.Count))+
# #   geom_bar()+
# #   labs(title='Mutations by Patient')+
# #   theme(plot.title = element_text(hjust = 0.5))
# 
# 
# boxplot1
# boxplot2
# boxplot3


```



```{r}

# corr_tcga.clinical.df <- tcga.clinical.df[c("Diagnosis.Age", "Mutation.Count", "Overall.Survival..Months.", "Patient.Weight", "Patient.Height")]
# 
# no_na_tcga.clinical.df <- na.omit(corr_tcga.clinical.df)
# 
# agg_df_num <- no_na_tcga.clinical.df %>% count(Diagnosis.Age, Mutation.Count, Overall.Survival..Months., Patient.Height, Patient.Weight, sort = TRUE)
# corr_df <- subset(agg_df_num, select = -c(n))
# 
# corrplot(cor(corr_df), method = 'number', title = "Correlation of Various Numeric Values", mar=c(0,0,1,0))

```